### PR TITLE
Update build.cmd

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by adabadadudu** [comment]
i say that you develop this file because I don't understand DOS-Batch-CMD but if you see in the build.sh source you see variables like cc and others then I merge it with a lot of thanks.

**Comment by mehanalavimajd** [comment]
@hasan-kashi  , I think @PooiaFerdowsi  is right you can develop this .cmd file

**Comment by adabadadudu** [comment]
Dear @hasan-kashi I create the codeowners file .

this means you can develop this file .

don't send any pull request because ***You are at branch-master(main) for the build.cmd file***

**Comment by adabadadudu** [comment]
That now you can close your pull request

**Pull request merged**
