### PR TITLE
Documentation enhancements

### PR DESCRIPTION
**Pull request by Amohammadi2**
+ Fixed some grammatical mistakes.
+ Made sentences more readable

### CODE REVIEW

**Comment by adabadadudu** [comment]
# Thank you
thank you for your contribute for Pandex
# But
but your PR contains a mistake . no in English syntax , you don't understand my mean. I change PR . 
__*Please* see `STRUCT` file , what's mean of `'` after `identifier` in file__

to 100 percent I merge this pull request

**Comment by adabadadudu** [comment]
after change local source I merge 
----------------------------------------------
Thanks you

[Nice You joined Pandex](https://github.com/Pandex-lang/Pandex/blob/main/no_README.md)
=================================================================

**Comment by adabadadudu** [comment]
Are you ready for merge ?
~~~~~~~~~~~~~~~~~~~~

will merge in less than 30 second after sending this messsage

**Comment by Amohammadi2** [comment]
Thank you for merging my PR

**Comment by adabadadudu** [comment]
I am thank you for contribution

**Pull request merged**
